spring.application.name=EMS_Project
spring.datasource.url=jdbc:postgresql://localhost:5432/emp_db
spring.datasource.username=postgres
spring.datasource.password=Rohit1402

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.Spring.API.EMS_Project=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.level.org.springframework.security=DEBUG